### ISSUE TITLE
Ошибка перевода (блок watchEffect)

### ISSUE THREAD

**Issue by Zaurinio** [vuejs-translations/docs-ru#374]
В переводе блока watchEffect (https://vuejs-doc-ru.vercel.app/guide/essentials/watchers.html#watcheffect) текст первого параграфа взят из блока Eager Watchers (https://vuejs-doc-ru.vercel.app/guide/essentials/watchers.html#eager-watchers).

В документации на английском другой текст (https://vuejs.org/guide/essentials/watchers.html#watcheffect).

**Comment by farid-temuri** [comment]
Возьму @Zaurinio

**Comment by Hekikai** [comment]
@farid-temuri что по статусу? Я могу взять вдруг что

**Comment by farid-temuri** [comment]
@Hekikai Бери, у меня планы поменялись

**Comment by mnenie** [comment]
@Hekikai могу сделать, если статус тот же.

**Comment by Hekikai** [comment]
@mnenie да, бери, спасибо!
