### ISSUE TITLE
Ошибка перевода (блок 'Ссылка на компонент')

### ISSUE THREAD

**Issue by Zaurinio** [vuejs-translations/docs-ru#375]
В переводе блока 'Ссылка на компонент' (https://vuejs-doc-ru.vercel.app/guide/essentials/template-refs.html#ref-on-component) отсутствует часть текста.

После текста "Если дочерний компонент использует Options API или не использует <script setup>," перевод обрывается.

**Comment by Hekikai** [comment]
Спасибо, возьму на себя
