### ISSUE TITLE
Поменять ссылку в описании

### ISSUE THREAD

**Issue by farid-temuri** [vuejs-translations/docs-ru#376]
<img width="203" alt="Screenshot 2024-03-26 at 00 37 29" src="https://github.com/vuejs-translations/docs-ru/assets/56141667/926532b7-0304-41a2-94d5-d507b2f741bc">

Мы же точно уже знаем куда будет деплой.

**Comment by Hekikai** [comment]
@farid-temuri подскажи, где будет деплой?

**Comment by Ibochkarev** [comment]
@Hekikai ru.vuejs.org

**Comment by Hekikai** [comment]
@Ibochkarev у меня нет прав, нет шестеренки справа

**Comment by Ibochkarev** [comment]
Поменял, спасибо!
