### ISSUE TITLE
Ошибка перевода (блок 'Валидация входных параметров')

### ISSUE THREAD

**Issue by Zaurinio** [vuejs-translations/docs-ru#377]
В переводе блока 'Валидация входных параметров' (https://vuejs-doc-ru.vercel.app/guide/components/props.html#prop-validation) отсутствует перевод части комментария: "// Пользовательская функция для валидации
  // full props passed as 2nd argument in 3.4+"

**Comment by srsad** [comment]
Беру

**Comment by Hekikai** [comment]
Закрываю по причине мерджа
