### ISSUE TITLE
Ошибка перевода (блок 'Булево преобразование')

### ISSUE THREAD

**Issue by Zaurinio** [vuejs-translations/docs-ru#378]
В переводе блока 'Булево преобразование' (https://vuejs-doc-ru.vercel.app/guide/components/props.html#boolean-casting) в последнем абзаце пропущена часть текста.

В англоязычной версии: 
"When a prop is declared to allow multiple types, the casting rules for Boolean will also be applied. However, there is an edge when both String and Boolean are allowed - the Boolean casting rule only applies if Boolean appears before String:"

В русскоязычной версии: 
"Когда входной параметр объявлен так, что допускает несколько типов, например:"

**Comment by Hekikai** [comment]
Беру!
