### ISSUE TITLE
Ошибка перевода (блок "Валидация сгенерированных событий")

### ISSUE THREAD

**Issue by Zaurinio** [vuejs-translations/docs-ru#381]
В переводе блока "Валидация сгенерированных событий" (https://vuejs-doc-ru.vercel.app/guide/components/events.html#events-validation) ошибка в переводе первого абзаца.

Текст на английском:
"Similar to prop type validation, an emitted event can be validated if it is defined with the object syntax instead of the array syntax."

Текст на русском:
"Аналогично валидации входных параметров, генерируемые события также могут быть валидированы, если это определено с помощью объектного синтаксиса или синтаксиса массива."

Валидация с помощью синтаксиса массива недоступна.

**Comment by Hekikai** [comment]
Возьму на себя
