### ISSUE TITLE
Ошибка перевода (блок "v-model")

### ISSUE THREAD

**Issue by Zaurinio** [vuejs-translations/docs-ru#382]
Информация из первого абзаца в переводе блока "v-model" отсутствует в англоязычной версии:
"Нормализует значения / ref-объекты / геттеры к значениям. Это похоже на [unref()](https://vuejs-doc-ru.vercel.app/guide/components/v-model.html#unref), с той лишь разницей, что оно также нормализует геттеры. Если аргумент является геттером, то он будет вызван, и будет возвращено его возвращаемое значение."

Данная информация относится к v-model?

**Comment by Hekikai** [comment]
Возьму на себя, проверю)
