### ISSUE TITLE
Компонент поиска по докуметации

### ISSUE THREAD

**Issue by mnenie** [vuejs-translations/docs-ru#400]
@Ibochkarev Будете ли делать и добавлять компонент и его функционал для поиска по документации? Или он есть и просто не добавлен

EN и не только: 
<img width="284" alt="Снимок экрана 2024-04-06 в 20 19 00" src="https://github.com/vuejs-translations/docs-ru/assets/121057011/cb088c06-b770-4790-a6e2-97821fb86408">

RU: 
<img width="577" alt="Снимок экрана 2024-04-06 в 20 19 28" src="https://github.com/vuejs-translations/docs-ru/assets/121057011/a3735069-9e37-49dc-9579-1ae10ad4a99b">

**Comment by Ibochkarev** [comment]
@mnenie привет!

Проверим, почему не работает у нас

**Comment by Ibochkarev** [comment]
![image](https://github.com/vuejs-translations/docs-ru/assets/2138260/8758686f-57e4-4022-954b-151d0081b452)

Реализовано
